[package]
name = "led-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
chrono = { version = "0.4.34", features = ["serde"] }
console-subscriber = "0.2.0"
embedded-graphics = "0.8.1"
env_logger = "0.11.2"
human-panic = "1.2.3"
log = "0.4.20"
postgrest = "1.6.0"
reqwest = { version = "0.11.24", features = [
  "json",
  "rustls",
  "rustls-tls",
  "tokio-rustls",
], default-features = false }
rpi-led-panel = "0.5.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full", "tracing"] }
tracing = "0.1.40"
