[package]
name = "led-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
argh = "0.1.12"
axum = "0.6.20"
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
clap = { version = "4.4.11", features = ["derive"] }
embedded-graphics = "0.8.1"
embedded-graphics-simulator = { version = "0.5.0", default_features = false }
env_logger = "0.10.1"
human-panic = "1.2.2"
log = "0.4.20"
rpi-led-panel = "0.5.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["full"] }
tower-http = { version = "0.4.4", features = ["trace", "cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
